version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:5.1.2
    container_name: logstash
    links:
      - elasticsearch
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/:ro
    ports:
      - "5044:5044"
      - "9300:9300"
      - "9600:9600"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.1.2
    container_name: kibana
    links:
      - elasticsearch
    ports:
      - "5601:5601"
